platform:'ios', '8.0'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'YYModel'
pod 'SDWebImage'
pod 'BmobSDK'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJPhotoBrowser', '~> 1.0.2'
pod 'NJKWebViewProgress', '~> 0.2.3'
